CREATE DATABASE GUFLIX

USE GUFLIX
GO

CREATE TABLE Usuario(
IdUser INT PRIMARY KEY IDENTITY NOT NULL,
UserName VARCHAR(256) NOT NULL,
Email VARCHAR(256) NOT NULL UNIQUE,
Passwd VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE Filme(
IdFilme INT PRIMARY KEY IDENTITY NOT NULL,
NomeFilme VARCHAR(70),
Genero VARCHAR(70)
)
GO